ci functional

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,170 +12,198 @@ on:
     types: [opened]
 
 jobs:
-  # lint:
-  #   if: contains(github.event.head_commit.message, 'Send QA')
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout the code
-  #       uses: actions/checkout@v2
-  #
-  #     - name: Set up JDK 17
-  #       uses: actions/setup-java@v3
-  #       with:
-  #         java-version: '17'
-  #         distribution: 'temurin' # Usar la distribución de Temurin
-  #
-  #     - name: Grant execute permission for gradlew
-  #       run: chmod +x ./gradlew
-  #
-  #     - name: Run Lint
-  #       run: ./gradlew lint
-  #
-  #     - name: Debug artifacts
-  #       run: ls -R app/build/reports
-  #
-  #     - name: Upload html test report
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: lint-report
-  #         path: app/build/reports/lint-results-debug.html
-  #
-  # unit-test:
-  #     needs: [ lint ]
-  #     runs-on: ubuntu-latest
-  #     steps:
-  #       - name: Checkout the code
-  #         uses: actions/checkout@v2
-  #
-  #       - name: Set up JDK 17
-  #         uses: actions/setup-java@v3
-  #         with:
-  #           java-version: '17'
-  #           distribution: 'temurin' # Usar la distribución de Temurin
-  #
-  #       - name: Grant execute permission for gradlew
-  #         run: chmod +x ./gradlew
-  #
-  #       - name: Run tests
-  #         run: ./gradlew test
-  #
-  #       - name: Upload test report
-  #         uses: actions/upload-artifact@v4
-  #         with:
-  #           name: unit_test_report
-  #           path: app/build/reports/tests/testDebugUnitTest/
+  lint:
+    if: contains(github.event.head_commit.message, 'Send QA')
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Install google-services.json (from secret)
+        env:
+          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
+        run: |
+          echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+
+      - name: Run Lint
+        run: ./gradlew lint
+
+      - name: Debug artifacts
+        run: ls -R app/build/reports
+
+      - name: Upload html test report
+        uses: actions/upload-artifact@v4
+        with:
+          name: lint-report
+          path: app/build/reports/lint-results-debug.html
+
+      - name: Clean sensitive files
+        if: ${{ always() }}
+        run: rm -f app/google-services.json
+
+  unit-test:
+    needs: [ lint ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Install google-services.json (from secret)
+        env:
+          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
+        run: |
+          echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+
+      - name: Run tests
+        run: ./gradlew test
+
+      - name: Upload test report
+        uses: actions/upload-artifact@v4
+        with:
+          name: unit_test_report
+          path: app/build/reports/tests/testDebugUnitTest/
+
+      - name: Clean sensitive files
+        if: ${{ always() }}
+        run: rm -f app/google-services.json
 
   instrumentation-test:
-      if: contains(github.event.head_commit.message, 'Send QA')
-      #needs: [ unit-test ]
-      runs-on: ubuntu-latest
-      strategy:
-        matrix:
-          api-level: [ 29 ]
-      steps:
-        - name: Checkout the code
-          uses: actions/checkout@v2
+    if: contains(github.event.head_commit.message, 'Send QA')
+    needs: [ unit-test ]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        api-level: [ 29 ]
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v2
 
-        - name: Set up JDK 17
-          uses: actions/setup-java@v3
-          with:
-            java-version: '17'
-            distribution: 'temurin'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-        - name: Install google-services.json (from secret)
-          env:
-            GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
-          run: |
-            echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
+      - name: Install google-services.json (from secret)
+        env:
+          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
+        run: |
+          echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
 
-        - name: Grant execute permission for gradlew
-          run: chmod +x ./gradlew
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
 
-        - name: Run espresso tests
-          uses: reactivecircus/android-emulator-runner@v2
-          with:
-            api-level: 29 # Usa API 29 para mejor compatibilidad
-            target: default
-            arch: x86_64
-            profile: Nexus 6
-            emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-            disable-animations: true
-            script: ./gradlew connectedCheck --stacktrace
+      - name: Run espresso tests
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: 29
+          target: default
+          arch: x86_64
+          profile: Nexus 6
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: ./gradlew connectedCheck --stacktrace
 
-        - name: Upload test report
-          if: always()
-          uses: actions/upload-artifact@v4
-          with:
-            name: instrumentation_test_report
-            path: app/build/reports/androidTests/connected/
+      - name: Upload test report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: instrumentation_test_report
+          path: app/build/reports/androidTests/connected/
 
-        - name: Clean sensitive files
-          if: ${{ always() }}
-          run: rm -f app/google-services.json
-  sonarcloud:
-      needs: [ instrumentation-test ]
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout the code
-          uses: actions/checkout@v3
-          with:
-            fetch-depth: 0
+      - name: Clean sensitive files
+        if: ${{ always() }}
+        run: rm -f app/google-services.json
 
-        - name: Set up JDK 17
-          uses: actions/setup-java@v3
-          with:
-            java-version: '17'
-            distribution: 'temurin'
+  sonarqube:
+    needs: [ instrumentation-test ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-        - name: Install google-services.json (from secret)
-          env:
-            GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
-          run: |
-            echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-        - name: Grant execute permission for gradlew
-          run: chmod +x ./gradlew
+      - name: Install google-services.json (from secret)
+        env:
+          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
+        run: |
+          echo -n "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
 
-        - name: Cache Gradle packages
-          uses: actions/cache@v3
-          with:
-            path: |
-              ~/.gradle/caches
-              ~/.gradle/wrapper
-            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-            restore-keys: |
-              ${{ runner.os }}-gradle
-        - name: Build and run tests with coverage
-          run: ./gradlew clean build jacocoTestReport
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
 
-        - name: SonarCloud Scan
-          run: ./gradlew app:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
-          env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Cache Gradle packages
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle
 
-        - name: Upload coverage report
-          uses: actions/upload-artifact@v4
-          with:
-            name: coverage-report
-            path: build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
+      - name: Build and run tests with coverage
+        run: ./gradlew clean build jacocoTestReport
 
-        - name: Check SonarQube Quality Gate
-          run: |
-            status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarqube.capibarafamily.online/api/qualitygates/project_status?projectKey=Portfolio_kotlin&branch=main" | jq -r '.projectStatus.status')
-            if [ "$status" != "OK" ]; then
-              echo "Quality gate failed: $status"
-              exit 1
-            fi
-          env:
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: SonarQube Scan
+        run: >
+          ./gradlew app:sonar
+          -Dsonar.host.url=https://sonarqube.capibarafamily.online
+          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-        - name: Clean sensitive files
-          if: ${{ always() }}
-          run: rm -f app/google-services.json
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report
+          path: build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
+
+      - name: Check SonarQube Quality Gate
+        run: |
+          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+            "https://sonarqube.capibarafamily.online/api/qualitygates/project_status?projectKey=Portfolio_kotlin&branch=main" \
+            | jq -r '.projectStatus.status')
+          if [ "$status" != "OK" ]; then
+            echo "Quality gate failed: $status"
+            exit 1
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Clean sensitive files
+        if: ${{ always() }}
+        run: rm -f app/google-services.json
+
   Firebase:
-      needs: [ sonarcloud ]
-      runs-on: ubuntu-latest
-      steps:
+    needs: [ sonarqube ]
+    runs-on: ubuntu-latest
+    steps:
       - name: Checkout the code
         uses: actions/checkout@v2
 
