avance

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,9 +34,23 @@ jobs:
 
       - name: Download gdrive binary
         run: |
-          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-amd64 -O gdrive
+          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64 -O gdrive
           chmod +x gdrive
-          ./gdrive version
+          file_size=$(stat -c %s gdrive)
+          if [ "$file_size" -gt 1000000 ]; then
+            echo "gdrive binary downloaded successfully."
+            head -c 10 gdrive | hexdump -C
+            if head -c 10 gdrive | grep -q "ELF"; then
+              echo "gdrive binary is an ELF file."
+              ./gdrive version
+            else
+              echo "gdrive binary is not an ELF file."
+              exit 1
+            fi
+          else
+            echo "Failed to download gdrive binary. File size: $file_size"
+            exit 1
+          fi
 
       - name: Upload APK to Google Drive
         run: |
